server:
  port: 8082

spring:
  application:
    name: deepShearch\
  main:
    allow-bean-definition-overriding: true
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      max-age: 3600

  security:
    user:
      name: none
      password: none
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master
          jwk-set-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/certs
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:1.7b
    mcp:
      client:
        enabled: true
        name: StudyPlusAdminAIClient
        version: 1.0.0
        type: sync
        streamable-http:
          connections:
            StudyPlusAdminAIClient:
              url: http://localhost:8081
  datasource:
    url: jdbc:postgresql://localhost:5432/DeepShearch
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update # change to 'validate' in production
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE
    com.example.edumcpclient: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

host:
  mayan:
    url: http://192.168.40.255
