server:
  port: 8082

spring:
  application:
    name: edumcpclient\
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      max-age: 3600

  security:
    user:
      name: none
      password: none
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:1.7b
    mcp:
      client:
        enabled: true
        name: StudyPlusAdminAIClient
        version: 1.0.0
        type: sync
        streamable-http:
          connections:
            StudyPlusAdminAIClient:
              url: http://localhost:8081
  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update # change to 'validate' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: qw41wqe57r4we2qr4weq874we23qd43weq58ew74rqDFfFe7r2e7wf7ewf2v7F7
  expiration-30j: 25920000000

logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE
    com.example.edumcpclient: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
