server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: deepShearch
  main:
    allow-bean-definition-overriding: true
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      max-age: 3600

  security:
    user:
      name: none
      password: none
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${SPRING_AI_OLLAMA_CHAT_OPTIONS_MODEL:qwen3:1.7b}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/DeepShearch}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE
    com.example.edumcpclient: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

host:
  mayan:
    url: ${HOST_MAYAN_URL:http://127.0.0.1:80}
    username: ${HOST_MAYAN_USERNAME:admin}
    password : ${HOST_MAYAN_PASSWORD:RC6LhKSYrm}
  keycloak:
    realm: ${KEYCLOAK_REALM:MyRealmDeepSearch}
    auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080/auth}
    resource: ${KEYCLOAK_RESOURCE:backend-DeepSearch-service}
    credentials:
      secret: ${KEYCLOAK_SECRET:789c4e5f-1234-5678-9abc-def012345678}